export interface Course {
  available: number;
  enrollmentCount: number;
  abbreviation: string;
  number: number;
  type?: string; // for the RES & IND thing (idk what they mean)
  section: number;
  title: string;
  creditHour: number;
  begin: string;
  end: string;
  days: string;
  roomNumber: number;
  building?: string;
  instructor?: string;
  specialEnrollment?: string;
  lab?: { // or REC, idk what that mean
    begin?: string;
    end?: string;
    days?: string;
  }
}

export interface Department {
  departmentTitle: string;
  courses: Course[];
}

export interface Semester {
  semesterTitle: string;
  departments: Department[];
}

export const exampleDatabase: Semester[] = [
  {
    semesterTitle: "Spring 2024",
    departments: [
      {
        departmentTitle: "Computer Science",
        courses: [
            {
                "available": 32,
                "enrollmentCount": 18,
                "abbreviation": "CSC",
                "number": 1240,
                "section": 1,
                "title": "STATS & GRAPH MATLB",
                "creditHour": 3.0,
                "begin": "1130",
                "end": "1220",
                "days": "MW",
                "roomNumber": 1240,
                "building": "PATRICK TAYLOR",
                "instructor": "BRENER N"
            },
            {
                "available": 15,
                "enrollmentCount": 45,
                "abbreviation": "CSC",
                "number": 1253,
                "section": 1,
                "title": "COMP SCI WITH C++",
                "creditHour": 3.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 1236,
                "building": "PATRICK TAYLOR",
                "instructor": "LAFLEUR S"
            },
            {
                "available": 23,
                "enrollmentCount": 37,
                "abbreviation": "CSC",
                "number": 1253,
                "section": 2,
                "title": "COMP SCI WITH C++",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 1236,
                "building": "PATRICK TAYLOR",
                "instructor": "WALKER C"
            },
            {
                "available": 39,
                "enrollmentCount": 21,
                "abbreviation": "CSC",
                "number": 1254,
                "section": 1,
                "title": "COMP SCI 11 WITH C++",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 206,
                "building": "TUREAUD HALL",
                "instructor": "DUNCAN W"
            },
            {
                "available": 74,
                "enrollmentCount": 16,
                "abbreviation": "CSC",
                "number": 1350,
                "section": 1,
                "title": "COMP SCI I-MJRS",
                "creditHour": 4.0,
                "begin": "1030",
                "end": "1120",
                "days": "MWF",
                "roomNumber": 1221,
                "building": "PATRICK TAYLOR",
                "instructor": "DUNCAN W"
            },
            {
                "available": 82,
                "enrollmentCount": 8,
                "abbreviation": "CSC",
                "number": 1350,
                "section": 2,
                "title": "COMP SCI I-MJRS",
                "creditHour": 4.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 228,
                "building": "TUREAUD HALL",
                "instructor": "PACE L"
            },
            {
                "available": 27,
                "enrollmentCount": 63,
                "abbreviation": "CSC",
                "number": 1351,
                "section": 2,
                "title": "COMP SCI II-MJRS",
                "creditHour": 4.0,
                "begin": "930",
                "end": "1020",
                "days": "MWF",
                "roomNumber": 1221,
                "building": "PATRICK TAYLOR",
                "instructor": "NEUPANE A"
            },
            {
                "available": 81,
                "enrollmentCount": 9,
                "abbreviation": "CSC",
                "number": 1351,
                "section": 3,
                "title": "COMP SCI II-MJRS",
                "creditHour": 4.0,
                "begin": "230",
                "end": "0320",
                "days": "MWF",
                "roomNumber": 1263,
                "building": "PATRICK TAYLOR",
                "instructor": "BRENER N"
            },
            {
                "available": 30,
                "enrollmentCount": 60,
                "abbreviation": "CSC",
                "number": 1351,
                "section": 1,
                "title": "COMP SCI II-MJRS",
                "creditHour": 4.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 1221,
                "building": "PATRICK TAYLOR",
                "instructor": "BRANDT S"
            },
            {
                "available": 0,
                "enrollmentCount": 62,
                "abbreviation": "CSC",
                "number": 2259,
                "section": 1,
                "title": "DISCRETE STRUCTURES",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 1263,
                "building": "PATRICK TAYLOR",
                "instructor": "NEUPANE A"
            },
            {
                "available": 33,
                "enrollmentCount": 16,
                "abbreviation": "CSC",
                "number": 2259,
                "section": 2,
                "title": "DISCRETE STRUCTURES",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 2324,
                "building": "PATRICK TAYLOR",
                "instructor": "LAFLEUR S"
            },
            {
                "available": 0,
                "enrollmentCount": 70,
                "abbreviation": "CSC",
                "number": 2262,
                "section": 2,
                "title": "NUMERICAL METHODS",
                "creditHour": 3.0,
                "begin": "900",
                "end": "1020",
                "days": "TTH",
                "roomNumber": 1253,
                "building": "PATRICK TAYLOR",
                "instructor": "LAFLEUR S"
            },
            {
                "available": 0,
                "enrollmentCount": 80,
                "abbreviation": "CSC",
                "number": 2262,
                "section": 1,
                "title": "NUMERICAL METHODS",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 1200,
                "building": "PATRICK TAYLOR",
                "instructor": "BRENER N"
            },
            {
                "available": 15,
                "enrollmentCount": 55,
                "abbreviation": "CSC",
                "number": 2362,
                "section": 1,
                "title": "INTRO TO CYBERSECUR",
                "creditHour": 3.0,
                "begin": "300",
                "end": "0420",
                "days": "TTH",
                "roomNumber": 1221,
                "building": "PATRICK TAYLOR",
                "instructor": "DONZE D"
            },
            {
                "available": 14,
                "enrollmentCount": 66,
                "abbreviation": "CSC",
                "number": 2463,
                "section": 1,
                "title": "PROGMMG DGITL MEDIA",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 1253,
                "building": "PATRICK TAYLOR",
                "instructor": "WEBB A"
            },
            {
                "available": 4,
                "enrollmentCount": 46,
                "abbreviation": "CSC",
                "number": 2610,
                "section": 1,
                "title": "CLOUD & WEB PROGMNG",
                "creditHour": 3.0,
                "begin": "900",
                "end": "1020",
                "days": "TTH",
                "roomNumber": 2324,
                "building": "PATRICK TAYLOR",
                "instructor": "WANG Q"
            },
            {
                "available": 8,
                "enrollmentCount": 92,
                "abbreviation": "CSC",
                "number": 3102,
                "section": 1,
                "title": "ADV DATA STRUCTURES",
                "creditHour": 3.0,
                "begin": "300",
                "end": "0420",
                "days": "TTH",
                "roomNumber": 1200,
                "building": "PATRICK TAYLOR",
                "instructor": "SHAH R"
            },
            {
                "available": 0,
                "enrollmentCount": 61,
                "abbreviation": "CSC",
                "number": 3200,
                "section": 1,
                "title": "ETHICS IN COMPUTING",
                "creditHour": 1.0,
                "begin": "130",
                "end": "0220",
                "days": "M",
                "roomNumber": 1225,
                "building": "PATRICK TAYLOR",
                "instructor": "TRIANTAPHYLLO"
            },
            {
                "available": 36,
                "enrollmentCount": 24,
                "abbreviation": "CSC",
                "number": 3200,
                "section": 2,
                "title": "ETHICS IN COMPUTING",
                "creditHour": 1.0,
                "begin": "330",
                "end": "0420",
                "days": "M",
                "roomNumber": 1253,
                "building": "PATRICK TAYLOR",
                "instructor": "TRIANTAPHYLLO"
            },
            {
                "available": 0,
                "enrollmentCount": 80,
                "abbreviation": "CSC",
                "number": 3304,
                "section": 1,
                "title": "INTRO TO SYSTM PROG",
                "creditHour": 3.0,
                "begin": "1130",
                "end": "1220",
                "days": "MWF",
                "roomNumber": 1221,
                "building": "PATRICK TAYLOR",
                "instructor": "DONZE D"
            },
            {
                "available": 16,
                "enrollmentCount": 64,
                "abbreviation": "CSC",
                "number": 3304,
                "section": 2,
                "title": "INTRO TO SYSTM PROG",
                "creditHour": 3.0,
                "begin": "1200",
                "end": "0120",
                "days": "TTH",
                "roomNumber": 105,
                "building": "TUREAUD HALL",
                "instructor": "TRAMMELL D"
            },
            {
                "available": 0,
                "enrollmentCount": 81,
                "abbreviation": "CSC",
                "number": 3380,
                "section": 1,
                "title": "OBJ ORIENTED DESIGN",
                "creditHour": 3.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 1225,
                "building": "PATRICK TAYLOR",
                "instructor": "KAISER H"
            },
            {
                "available": 0,
                "enrollmentCount": 131,
                "abbreviation": "CSC",
                "number": 3501,
                "section": 1,
                "title": "COMP ORGANIZATN/DSN",
                "creditHour": 3.0,
                "begin": "1030",
                "end": "1120",
                "days": "MWF",
                "roomNumber": 1263,
                "building": "PATRICK TAYLOR",
                "instructor": "WANG H"
            },
            {
                "available": 46,
                "enrollmentCount": 34,
                "abbreviation": "CSC",
                "number": 4101,
                "section": 2,
                "title": "PROG LANGUAGES",
                "creditHour": 3.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 206,
                "building": "TUREAUD HALL",
                "instructor": "MAHMOUD A"
            },
            {
                "available": 0,
                "enrollmentCount": 82,
                "abbreviation": "CSC",
                "number": 4101,
                "section": 1,
                "title": "PROG LANGUAGES",
                "creditHour": 3.0,
                "begin": "300",
                "end": "0420",
                "days": "TTH",
                "roomNumber": 1263,
                "building": "PATRICK TAYLOR",
                "instructor": "MAHMOUD A"
            },
            {
                "available": 0,
                "enrollmentCount": 70,
                "abbreviation": "CSC",
                "number": 4103,
                "section": 1,
                "title": "OPERATING SYSTEMS",
                "creditHour": 3.0,
                "begin": "500",
                "end": "0620N",
                "days": "TTH",
                "roomNumber": 1263,
                "building": "PATRICK TAYLOR",
                "instructor": "CHEN F"
            },
            {
                "available": 8,
                "enrollmentCount": 72,
                "abbreviation": "CSC",
                "number": 4263,
                "section": 1,
                "title": "VIDEO GAME DESIGN",
                "creditHour": 3.0,
                "begin": "430",
                "end": "0550N",
                "days": "TTH",
                "roomNumber": 1253,
                "building": "PATRICK TAYLOR",
                "instructor": "SHEPHERD D"
            },
            {
                "available": 17,
                "enrollmentCount": 63,
                "abbreviation": "CSC",
                "number": 4330,
                "section": 1,
                "title": "SOFTWARE SYST DEVEL",
                "creditHour": 3.0,
                "begin": "330",
                "end": "0450",
                "days": "MW",
                "roomNumber": 1263,
                "building": "PATRICK TAYLOR",
                "instructor": "CARVER D"
            },
            {
                "available": 16,
                "enrollmentCount": 44,
                "abbreviation": "CSC",
                "number": 4332,
                "section": 1,
                "title": "SW QUALITY & TESTING",
                "creditHour": 3.0,
                "begin": "930",
                "end": "1020",
                "days": "MWF",
                "roomNumber": 1253,
                "building": "PATRICK TAYLOR",
                "instructor": "DONZE D"
            },
            {
                "available": 15,
                "enrollmentCount": 15,
                "abbreviation": "CSC",
                "number": 4343,
                "section": 1,
                "title": "APPLIED DEEP LEARN",
                "creditHour": 3.0,
                "begin": "1230",
                "end": "0320",
                "days": "F",
                "roomNumber": 2341,
                "building": "PATRICK TAYLOR",
                "instructor": "ZHANG J"
            },
            {
                "available": 0,
                "enrollmentCount": 74,
                "abbreviation": "CSC",
                "number": 4351,
                "section": 1,
                "title": "COMPILER CONSTRUCTN",
                "creditHour": 3.0,
                "begin": "900",
                "end": "1020",
                "days": "TTH",
                "roomNumber": 1221,
                "building": "PATRICK TAYLOR",
                "instructor": "BAUMGARTNER G"
            },
            {
                "available": 0,
                "enrollmentCount": 30,
                "abbreviation": "CSC",
                "number": 4360,
                "section": 1,
                "title": "MALWARE ANALYSIS/REV",
                "creditHour": 3.0,
                "begin": "330",
                "end": "0620",
                "days": "M",
                "roomNumber": 2317,
                "building": "PATRICK TAYLOR",
                "instructor": "RICHARD G"
            },
            {
                "available": 0,
                "enrollmentCount": 75,
                "abbreviation": "CSC",
                "number": 4402,
                "section": 1,
                "title": "INTR DATABSE MGT SYS",
                "creditHour": 3.0,
                "begin": "1200",
                "end": "0120",
                "days": "TTH",
                "roomNumber": 1253,
                "building": "PATRICK TAYLOR",
                "instructor": "CHEN J"
            },
            {
                "available": 0,
                "enrollmentCount": 63,
                "abbreviation": "CSC",
                "number": 4444,
                "section": 1,
                "title": "ARTIFICIAL INTELLIG",
                "creditHour": 3.0,
                "begin": "1200",
                "end": "0120",
                "days": "TTH",
                "roomNumber": 1240,
                "building": "PATRICK TAYLOR",
                "instructor": "JASIM M"
            },
            {
                "available": 13,
                "enrollmentCount": 37,
                "abbreviation": "CSC",
                "number": 4501,
                "section": 1,
                "title": "COMPUTER NETWORKS",
                "creditHour": 3.0,
                "begin": "430",
                "end": "0550N",
                "days": "TTH",
                "roomNumber": 1236,
                "building": "PATRICK TAYLOR",
                "instructor": "BOU-HARB E"
            },
            {
                "available": 25,
                "enrollmentCount": 15,
                "abbreviation": "CSC",
                "number": 4512,
                "section": 1,
                "title": "OPTIMIZATION",
                "creditHour": 3.0,
                "begin": "300",
                "end": "0420",
                "days": "TTH",
                "roomNumber": 117,
                "building": "TUREAUD HALL",
                "instructor": "TRIANTAPHYLLO"
            },
            {
                "available": 8,
                "enrollmentCount": 52,
                "abbreviation": "CSC",
                "number": 4562,
                "section": 1,
                "title": "MOBILE SEC & CRYPTO",
                "creditHour": 3.0,
                "begin": "130",
                "end": "0250",
                "days": "TTH",
                "roomNumber": 9,
                "building": "LOCKETT",
                "instructor": "WANG C"
            },
            {
                "available": 0,
                "enrollmentCount": 20,
                "abbreviation": "CSC",
                "number": 4700,
                "section": 1,
                "title": "WEB SEC & PEN TEST",
                "creditHour": 3.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 1240,
                "building": "PATRICK TAYLOR",
                "instructor": "VADREVU K"
            },
            {
                "available": 10,
                "enrollmentCount": 20,
                "abbreviation": "CSC",
                "number": 4740,
                "section": 1,
                "title": "BIG DATA TECH",
                "creditHour": 3.0,
                "begin": "900",
                "end": "1020",
                "days": "TTH",
                "roomNumber": 2341,
                "building": "PATRICK TAYLOR",
                "instructor": "LEE K"
            },
            {
                "available": 0,
                "enrollmentCount": 35,
                "abbreviation": "CSC",
                "number": 7101,
                "section": 1,
                "title": "PROGRAM LANG STRUCTS",
                "creditHour": 3.0,
                "begin": "300",
                "end": "0420",
                "days": "TTH",
                "roomNumber": 1240,
                "building": "PATRICK TAYLOR",
                "instructor": "BAUMGARTNER G"
            },
            {
                "available": 0,
                "enrollmentCount": 29,
                "abbreviation": "CSC",
                "number": 7700,
                "section": 1,
                "title": "WEB SEARCH & DATA AN",
                "creditHour": 3.0,
                "begin": "900",
                "end": "1020",
                "days": "TTH",
                "roomNumber": 124,
                "building": "TUREAUD HALL",
                "instructor": "SUN M"
            },
            {
                "available": 0,
                "enrollmentCount": 21,
                "abbreviation": "CSC",
                "number": 7700,
                "section": 2,
                "title": "WEB SEC & PEN TEST",
                "creditHour": 3.0,
                "begin": "1030",
                "end": "1150",
                "days": "TTH",
                "roomNumber": 1240,
                "building": "PATRICK TAYLOR",
                "instructor": "VADREVU K"
            }
        ],
      },
      {
        departmentTitle: "Mathematics",
        courses: [
          {
              "available": 33,
              "enrollmentCount": 7,
              "abbreviation": "MATH",
              "number": 1021,
              "section": 1,
              "title": "COLLEGE ALGEBRA",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "M",
              "roomNumber": 277,
              "building": "LOCKETT",
              "instructor": "WADDELL L"
          },
          {
              "available": 30,
              "enrollmentCount": 10,
              "abbreviation": "MATH",
              "number": 1029,
              "section": 1,
              "title": "INTRO CONTEMP MATH",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "MUFFULETTO M"
          },
          {
              "available": 205,
              "enrollmentCount": 45,
              "abbreviation": "MATH",
              "number": 1100,
              "section": 1,
              "title": "NATURE OF MATHEMATCS",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 143,
              "building": "COATES",
              "instructor": "DOUGHERTY E"
          },
          {
              "available": 24,
              "enrollmentCount": 14,
              "abbreviation": "MATH",
              "number": 1202,
              "section": 1,
              "title": "GEOM/REASONG/MEASURE",
              "creditHour": 3.0,
              "begin": " 900",
              "end": "1020 ",
              "days": "TTH",
              "roomNumber": 109,
              "building": "COATES",
              "instructor": "DOUGHERTY E"
          },
          {
              "available": 19,
              "enrollmentCount": 11,
              "abbreviation": "MATH",
              "number": 1202,
              "section": 2,
              "title": "GEOM/REASONG/MEASURE",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 109,
              "building": "COATES",
              "instructor": "DOUGHERTY E"
          },
          {
              "available": 23,
              "enrollmentCount": 12,
              "abbreviation": "MATH",
              "number": 1431,
              "section": 1,
              "title": "CAL-BUS & ECO APLCAT",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "LEDET J"
          },
          {
              "available": 14,
              "enrollmentCount": 15,
              "abbreviation": "MATH",
              "number": 1431,
              "section": 2,
              "title": "CAL-BUS & ECO APLCAT",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "LEDET J"
          },
          {
              "available": 0,
              "enrollmentCount": 35,
              "abbreviation": "MATH",
              "number": 1431,
              "section": 3,
              "title": "CAL-BUS & ECO APLCAT",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "LEDET J"
          },
          {
              "available": 13,
              "enrollmentCount": 7,
              "abbreviation": "MATH",
              "number": 1540,
              "section": 2,
              "title": "INTEGRAL CALCULUS",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "MWF",
              "roomNumber": 235,
              "building": "LOCKETT",
              "instructor": "VEMPATI N"
          },
          {
              "available": 29,
              "enrollmentCount": 1,
              "abbreviation": "MATH",
              "number": 1550,
              "section": 8,
              "title": "CALCULUS I",
              "creditHour": 5.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "MTWTH",
              "roomNumber": 5,
              "building": "LOCKETT",
              "instructor": "HARHAD A"
          },
          {
              "available": 0,
              "enrollmentCount": 50,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 2,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 930",
              "end": "1020 ",
              "days": "MTWTH",
              "roomNumber": 1022,
              "building": "CAMELLIA HALL",
              "instructor": "HOMAN T"
          },
          {
              "available": 151,
              "enrollmentCount": 39,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 4,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MTWTH",
              "roomNumber": 5,
              "building": "LOCKETT",
              "instructor": "SMOLINSKY L"
          },
          {
              "available": 74,
              "enrollmentCount": 16,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 1,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 730",
              "end": "0820 ",
              "days": "TWTF",
              "roomNumber": 5,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 0,
              "enrollmentCount": 15,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 7,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "TWTF",
              "roomNumber": 116,
              "building": "LOCKETT",
              "instructor": "TU F"
          },
          {
              "available": 44,
              "enrollmentCount": 36,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 8,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 500",
              "end": "0650N",
              "days": "TTH",
              "roomNumber": 155,
              "building": "COATES",
              "instructor": "ESTRADA R"
          },
          {
              "available": 0,
              "enrollmentCount": 30,
              "abbreviation": "MATH",
              "number": 1553,
              "section": 1,
              "title": "HON- AN GEOM CAL II",
              "creditHour": 4.0,
              "begin": " 730",
              "end": "0820 ",
              "days": "MTWTH",
              "roomNumber": 276,
              "building": "LOCKETT",
              "instructor": "HOMAN T"
          },
          {
              "available": 0,
              "enrollmentCount": 30,
              "abbreviation": "MATH",
              "number": 1553,
              "section": 2,
              "title": "HON- AN GEOM CAL II",
              "creditHour": 4.0,
              "begin": " 830",
              "end": "0920 ",
              "days": "TWTF",
              "roomNumber": 235,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 13,
              "enrollmentCount": 6,
              "abbreviation": "MATH",
              "number": 2030,
              "section": 1,
              "title": "DISCRETE DYNAMICALS",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 235,
              "building": "LOCKETT",
              "instructor": "WOLENSKI P"
          },
          {
              "available": 52,
              "enrollmentCount": 28,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 1,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "MWF",
              "roomNumber": 10,
              "building": "LOCKETT",
              "instructor": "SINGH R"
          },
          {
              "available": 43,
              "enrollmentCount": 37,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 2,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 152,
              "building": "COATES",
              "instructor": "TARFULEA A"
          },
          {
              "available": 75,
              "enrollmentCount": 5,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 3,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 6,
              "building": "LOCKETT",
              "instructor": "DRENSKA N"
          },
          {
              "available": 0,
              "enrollmentCount": 80,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 4,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250 ",
              "days": "TTH",
              "roomNumber": 228,
              "building": "COATES",
              "instructor": "SCHREVE K"
          },
          {
              "available": 71,
              "enrollmentCount": 9,
              "abbreviation": "MATH",
              "number": 2065,
              "section": 2,
              "title": "EL DIFFERENTIAL EQ",
              "creditHour": 3.0,
              "begin": " 900",
              "end": "1020 ",
              "days": "TTH",
              "roomNumber": 16,
              "building": "LOCKETT",
              "instructor": "RUBIN B"
          },
          {
              "available": 34,
              "enrollmentCount": 46,
              "abbreviation": "MATH",
              "number": 2065,
              "section": 3,
              "title": "EL DIFFERENTIAL EQ",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 109,
              "building": "NICHOLSON",
              "instructor": "MALISOFF M"
          },
          {
              "available": 58,
              "enrollmentCount": 22,
              "abbreviation": "MATH",
              "number": 2070,
              "section": 1,
              "title": "MATH METH IN ENGINEE",
              "creditHour": 4.0,
              "begin": " 930",
              "end": "1020 ",
              "days": "TWTF",
              "roomNumber": 228,
              "building": "COATES",
              "instructor": "OLAFSSON G"
          },
          {
              "available": 58,
              "enrollmentCount": 22,
              "abbreviation": "MATH",
              "number": 2070,
              "section": 2,
              "title": "MATH METH IN ENGINEE",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "TWTF",
              "roomNumber": 228,
              "building": "COATES",
              "instructor": "OLAFSSON G"
          },
          {
              "available": 24,
              "enrollmentCount": 16,
              "abbreviation": "MATH",
              "number": 2085,
              "section": 1,
              "title": "LINEAR ALGEBRA",
              "creditHour": 3.0,
              "begin": "1130",
              "end": "1220 ",
              "days": "MWF",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "HOMAN T"
          },
          {
              "available": 32,
              "enrollmentCount": 48,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 1,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": " 930",
              "end": "1020 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "AZHANG A"
          },
          {
              "available": 50,
              "enrollmentCount": 30,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 2,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "AZHANG A"
          },
          {
              "available": 39,
              "enrollmentCount": 41,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 3,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "AZHANG A"
          },
          {
              "available": 53,
              "enrollmentCount": 27,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 4,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "HAN R"
          },
          {
              "available": 4,
              "enrollmentCount": 36,
              "abbreviation": "MATH",
              "number": 3355,
              "section": 1,
              "title": "PROBABILITY",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 138,
              "building": "LOCKETT",
              "instructor": "LIPTON R"
          },
          {
              "available": 22,
              "enrollmentCount": 3,
              "abbreviation": "MATH",
              "number": 4005,
              "section": 1,
              "title": "GEOMETRY",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 116,
              "building": "LOCKETT",
              "instructor": "DANI P"
          },
          {
              "available": 10,
              "enrollmentCount": 9,
              "abbreviation": "MATH",
              "number": 4024,
              "section": 1,
              "title": "MATHEMATICAL MODELS",
              "creditHour": 3.0,
              "begin": " 300",
              "end": "0420 ",
              "days": "TTH",
              "roomNumber": 285,
              "building": "LOCKETT",
              "instructor": "MASSATT D"
          },
          {
              "available": 5,
              "enrollmentCount": 14,
              "abbreviation": "MATH",
              "number": 4025,
              "section": 1,
              "title": "OPTIMIZATION THY-APP",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 18,
              "enrollmentCount": 1,
              "abbreviation": "MATH",
              "number": 4027,
              "section": 1,
              "title": "DIFFERENTIAL EQU",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 116,
              "building": "LOCKETT",
              "instructor": "RUBIN B"
          },
          {
              "available": 17,
              "enrollmentCount": 21,
              "abbreviation": "MATH",
              "number": 4031,
              "section": 1,
              "title": "ADVANCED CALCULUS I",
              "creditHour": 3.0,
              "begin": " 230",
              "end": "0320 ",
              "days": "MWF",
              "roomNumber": 136,
              "building": "LOCKETT",
              "instructor": "RICHARDSON L"
          },
          {
              "available": 11,
              "enrollmentCount": 8,
              "abbreviation": "MATH",
              "number": 4032,
              "section": 1,
              "title": "ADVANCED CALCULUS II",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 138,
              "building": "LOCKETT",
              "instructor": "RICHARDSON L"
          },
          {
              "available": 17,
              "enrollmentCount": 11,
              "abbreviation": "MATH",
              "number": 4036,
              "section": 1,
              "title": "COMPLEX VARIABLES",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250 ",
              "days": "TTH",
              "roomNumber": 284,
              "building": "LOCKETT",
              "instructor": "ANTIPOV Y"
          },
          {
              "available": 29,
              "enrollmentCount": 11,
              "abbreviation": "MATH",
              "number": 4041,
              "section": 1,
              "title": "SHORTTERM ACT MATH2",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 276,
              "building": "LOCKETT",
              "instructor": "SMOLINSKY L"
          },
          {
              "available": 9,
              "enrollmentCount": 10,
              "abbreviation": "MATH",
              "number": 4058,
              "section": 1,
              "title": "ELEM STOCH PROCESSES",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 113,
              "building": "LOCKETT",
              "instructor": "GANGULY A"
          },
          {
              "available": 5,
              "enrollmentCount": 14,
              "abbreviation": "MATH",
              "number": 4153,
              "section": 1,
              "title": "FIN DIM VECT SPAC",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "MWF",
              "roomNumber": 134,
              "building": "LOCKETT",
              "instructor": "WU A"
          },
          {
              "available": 13,
              "enrollmentCount": 6,
              "abbreviation": "MATH",
              "number": 4171,
              "section": 1,
              "title": "THEORY OF GRAPHS",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "MWF",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "DING G"
          },
          {
              "available": 18,
              "enrollmentCount": 1,
              "abbreviation": "MATH",
              "number": 4201,
              "section": 1,
              "title": "ABSTRACT ALGEBRA II",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 243,
              "building": "LOCKETT",
              "instructor": "KOPP G"
          },
          {
              "available": 11,
              "enrollmentCount": 8,
              "abbreviation": "MATH",
              "number": 4325,
              "section": 1,
              "title": "FOURIER TRANSFORMS",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250 ",
              "days": "TTH",
              "roomNumber": 285,
              "building": "LOCKETT",
              "instructor": "MASSATT D"
          }
      ],
      },
    ]
  },
  {
    semesterTitle: "Fall 2023",
    departments: [
      {
        departmentTitle: "Computer Science",
        courses: [
          {
              "available": 37,
              "enrollmentCount": 13,
              "abbreviation": "CSC",
              "number": 1240,
              "section": 1,
              "title": "STATS & GRAPH MATLB",
              "creditHour": 3.0,
              "begin": "1130",
              "end": "1220",
              "days": "MW",
              "roomNumber": 1240,
              "building": "PATRICK TAYLOR",
              "instructor": "BRENER N"
          },
          {
              "available": 26,
              "enrollmentCount": 34,
              "abbreviation": "CSC",
              "number": 1253,
              "section": 1,
              "title": "COMP SCI WITH C++",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150",
              "days": "TTH",
              "roomNumber": 1236,
              "building": "PATRICK TAYLOR",
              "instructor": "LAFLEUR S"
          },
          {
              "available": 38,
              "enrollmentCount": 22,
              "abbreviation": "CSC",
              "number": 1253,
              "section": 2,
              "title": "COMP SCI WITH C++",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250",
              "days": "TTH",
              "roomNumber": 1236,
              "building": "PATRICK TAYLOR",
              "instructor": "WALKER C"
          },
          {
              "available": 49,
              "enrollmentCount": 11,
              "abbreviation": "CSC",
              "number": 1254,
              "section": 1,
              "title": "COMP SCI 11 WITH C++",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250",
              "days": "TTH",
              "roomNumber": 206,
              "building": "TUREAUD HALL",
              "instructor": "DUNCAN W"
          },
          {
              "available": 80,
              "enrollmentCount": 10,
              "abbreviation": "CSC",
              "number": 1350,
              "section": 1,
              "title": "COMP SCI I-MJRS",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120",
              "days": "MWF",
              "roomNumber": 1221,
              "building": "PATRICK TAYLOR",
              "instructor": "DUNCAN W"
          },
          {
              "available": 45,
              "enrollmentCount": 45,
              "abbreviation": "CSC",
              "number": 1351,
              "section": 2,
              "title": "COMP SCI II-MJRS",
              "creditHour": 4.0,
              "begin": "930",
              "end": "1020",
              "days": "MWF",
              "roomNumber": 1221,
              "building": "PATRICK TAYLOR",
              "instructor": "NEUPANE A"
          },
          {
              "available": 88,
              "enrollmentCount": 2,
              "abbreviation": "CSC",
              "number": 1351,
              "section": 3,
              "title": "COMP SCI II-MJRS",
              "creditHour": 4.0,
              "begin": "230",
              "end": "0320",
              "days": "MWF",
              "roomNumber": 1263,
              "building": "PATRICK TAYLOR",
              "instructor": "BRENER N"
          },
          {
              "available": 51,
              "enrollmentCount": 39,
              "abbreviation": "CSC",
              "number": 1351,
              "section": 1,
              "title": "COMP SCI II-MJRS",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1150",
              "days": "TTH",
              "roomNumber": 1221,
              "building": "PATRICK TAYLOR",
              "instructor": "MAHMOUD A"
          },
          {
              "available": 47,
              "enrollmentCount": 53,
              "abbreviation": "CSC",
              "number": 2259,
              "section": 1,
              "title": "DISCRETE STRUCTURES",
              "creditHour": 3.0,
              "begin": "130",
              "end": "0250",
              "days": "TTH",
              "roomNumber": 1263,
              "building": "PATRICK TAYLOR",
              "instructor": "NEUPANE A"
          },
          {
              "available": 0,
              "enrollmentCount": 70,
              "abbreviation": "CSC",
              "number": 2262,
              "section": 2,
              "title": "NUMERICAL METHODS",
              "creditHour": 3.0,
              "begin": "900",
              "end": "1020",
              "days": "TTH",
              "roomNumber": 1253,
              "building": "PATRICK TAYLOR",
              "instructor": "LAFLEUR S"
          },
          {
              "available": 37,
              "enrollmentCount": 43,
              "abbreviation": "CSC",
              "number": 2262,
              "section": 1,
              "title": "NUMERICAL METHODS",
              "creditHour": 3.0,
              "begin": "130",
              "end": "0250",
              "days": "TTH",
              "roomNumber": 1200,
              "building": "PATRICK TAYLOR",
              "instructor": "BRENER N"
          },
          {
              "available": 31,
              "enrollmentCount": 39,
              "abbreviation": "CSC",
              "number": 2362,
              "section": 1,
              "title": "INTRO TO CYBERSECUR",
              "creditHour": 3.0,
              "begin": "300",
              "end": "0420",
              "days": "TTH",
              "roomNumber": 1221,
              "building": "PATRICK TAYLOR",
              "instructor": "DONZE D"
          },
          {
              "available": 18,
              "enrollmentCount": 62,
              "abbreviation": "CSC",
              "number": 2463,
              "section": 1,
              "title": "PROGMMG DGITL MEDIA",
              "creditHour": 3.0,
              "begin": "130",
              "end": "0250",
              "days": "TTH",
              "roomNumber": 1253,
              "building": "PATRICK TAYLOR",
              "instructor": "WEBB A"
          },
          {
              "available": 38,
              "enrollmentCount": 62,
              "abbreviation": "CSC",
              "number": 3102,
              "section": 1,
              "title": "ADV DATA STRUCTURES",
              "creditHour": 3.0,
              "begin": "300",
              "end": "0420",
              "days": "TTH",
              "roomNumber": 1200,
              "building": "PATRICK TAYLOR",
              "instructor": "SHAH R"
          },
          {
              "available": 0,
              "enrollmentCount": 61,
              "abbreviation": "CSC",
              "number": 3200,
              "section": 1,
              "title": "ETHICS IN COMPUTING",
              "creditHour": 1.0,
              "begin": "130",
              "end": "0220",
              "days": "M",
              "roomNumber": 1225,
              "building": "PATRICK TAYLOR",
              "instructor": "TRIANTAPHYLLO"
          },
          {
              "available": 43,
              "enrollmentCount": 17,
              "abbreviation": "CSC",
              "number": 3200,
              "section": 2,
              "title": "ETHICS IN COMPUTING",
              "creditHour": 1.0,
              "begin": "330",
              "end": "0420",
              "days": "M",
              "roomNumber": 1253,
              "building": "PATRICK TAYLOR",
              "instructor": "TRIANTAPHYLLO"
          },
          {
              "available": 0,
              "enrollmentCount": 80,
              "abbreviation": "CSC",
              "number": 3304,
              "section": 1,
              "title": "INTRO TO SYSTM PROG",
              "creditHour": 3.0,
              "begin": "1130",
              "end": "1220",
              "days": "MWF",
              "roomNumber": 1221,
              "building": "PATRICK TAYLOR",
              "instructor": "DONZE D"
          },
          {
              "available": 0,
              "enrollmentCount": 81,
              "abbreviation": "CSC",
              "number": 3380,
              "section": 1,
              "title": "OBJ ORIENTED DESIGN",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150",
              "days": "TTH",
              "roomNumber": 1225,
              "building": "PATRICK TAYLOR",
              "instructor": "KAISER H"
          },
          {
              "available": 0,
              "enrollmentCount": 101,
              "abbreviation": "CSC",
              "number": 3501,
              "section": 1,
              "title": "COMP ORGANIZATN/DSN",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120",
              "days": "MWF",
              "roomNumber": 1263,
              "building": "PATRICK TAYLOR",
              "instructor": "WANG H"
          },
          {
              "available": 0,
              "enrollmentCount": 81,
              "abbreviation": "CSC",
              "number": 4101,
              "section": 1,
              "title": "PROG LANGUAGES",
              "creditHour": 3.0,
              "begin": "300",
              "end": "0420",
              "days": "TTH",
              "roomNumber": 1263,
              "building": "PATRICK TAYLOR",
              "instructor": "MAHMOUD A"
          },
          {
              "available": 20,
              "enrollmentCount": 60,
              "abbreviation": "CSC",
              "number": 4103,
              "section": 1,
              "title": "OPERATING SYSTEMS",
              "creditHour": 3.0,
              "begin": "500",
              "end": "0620N",
              "days": "TTH",
              "roomNumber": 1263,
              "building": "PATRICK TAYLOR",
              "instructor": "CHEN F"
          },
          {
              "available": 9,
              "enrollmentCount": 71,
              "abbreviation": "CSC",
              "number": 4263,
              "section": 1,
              "title": "VIDEO GAME DESIGN",
              "creditHour": 3.0,
              "begin": "430",
              "end": "0550N",
              "days": "TTH",
              "roomNumber": 1253,
              "building": "PATRICK TAYLOR",
              "instructor": "SHEPHERD D"
          },
          {
              "available": 18,
              "enrollmentCount": 62,
              "abbreviation": "CSC",
              "number": 4330,
              "section": 1,
              "title": "SOFTWARE SYST DEVEL",
              "creditHour": 3.0,
              "begin": "330",
              "end": "0450",
              "days": "MW",
              "roomNumber": 1263,
              "building": "PATRICK TAYLOR",
              "instructor": "CARVER D"
          },
          {
              "available": 19,
              "enrollmentCount": 41,
              "abbreviation": "CSC",
              "number": 4332,
              "section": 1,
              "title": "SW QUALITY & TESTING",
              "creditHour": 3.0,
              "begin": "930",
              "end": "1020",
              "days": "MWF",
              "roomNumber": 1253,
              "building": "PATRICK TAYLOR",
              "instructor": "DONZE D"
          },
          {
              "available": 15,
              "enrollmentCount": 15,
              "abbreviation": "CSC",
              "number": 4343,
              "section": 1,
              "title": "APPLIED DEEP LEARN",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0320",
              "days": "F",
              "roomNumber": 2341,
              "building": "PATRICK TAYLOR",
              "instructor": "ZHANG J"
          },
          {
              "available": 0,
              "enrollmentCount": 71,
              "abbreviation": "CSC",
              "number": 4351,
              "section": 1,
              "title": "COMPILER CONSTRUCTN",
              "creditHour": 3.0,
              "begin": "900",
              "end": "1020",
              "days": "TTH",
              "roomNumber": 1221,
              "building": "PATRICK TAYLOR",
              "instructor": "BAUMGARTNER G"
          },
          {
              "available": 0,
              "enrollmentCount": 31,
              "abbreviation": "CSC",
              "number": 4360,
              "section": 1,
              "title": "MALWARE ANALYSIS/REV",
              "creditHour": 3.0,
              "begin": "330",
              "end": "0620",
              "days": "M",
              "roomNumber": 2317,
              "building": "PATRICK TAYLOR",
              "instructor": "RICHARD G"
          },
          {
              "available": 0,
              "enrollmentCount": 75,
              "abbreviation": "CSC",
              "number": 4402,
              "section": 1,
              "title": "INTR DATABSE MGT SYS",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120",
              "days": "TTH",
              "roomNumber": 1253,
              "building": "PATRICK TAYLOR",
              "instructor": "CHEN J"
          },
          {
              "available": 0,
              "enrollmentCount": 53,
              "abbreviation": "CSC",
              "number": 4444,
              "section": 1,
              "title": "ARTIFICIAL INTELLIG",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120",
              "days": "TTH",
              "roomNumber": 1240,
              "building": "PATRICK TAYLOR",
              "instructor": "JASIM M"
          },
          {
              "available": 15,
              "enrollmentCount": 35,
              "abbreviation": "CSC",
              "number": 4501,
              "section": 1,
              "title": "COMPUTER NETWORKS",
              "creditHour": 3.0,
              "begin": "430",
              "end": "0550N",
              "days": "TTH",
              "roomNumber": 1236,
              "building": "PATRICK TAYLOR",
              "instructor": "BOU-HARB E"
          },
          {
              "available": 24,
              "enrollmentCount": 16,
              "abbreviation": "CSC",
              "number": 4512,
              "section": 1,
              "title": "OPTIMIZATION",
              "creditHour": 3.0,
              "begin": "300",
              "end": "0420",
              "days": "TTH",
              "roomNumber": 117,
              "building": "TUREAUD HALL",
              "instructor": "TRIANTAPHYLLO"
          },
          {
              "available": 0,
              "enrollmentCount": 20,
              "abbreviation": "CSC",
              "number": 4700,
              "section": 1,
              "title": "WEB SEC & PEN TEST",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150",
              "days": "TTH",
              "roomNumber": 1240,
              "building": "PATRICK TAYLOR",
              "instructor": "VADREVU K"
          },
          {
              "available": 11,
              "enrollmentCount": 19,
              "abbreviation": "CSC",
              "number": 4740,
              "section": 1,
              "title": "BIG DATA TECH",
              "creditHour": 3.0,
              "begin": "900",
              "end": "1020",
              "days": "TTH",
              "roomNumber": 2341,
              "building": "PATRICK TAYLOR",
              "instructor": "LEE K"
          },
          {
              "available": 0,
              "enrollmentCount": 35,
              "abbreviation": "CSC",
              "number": 7101,
              "section": 1,
              "title": "PROGRAM LANG STRUCTS",
              "creditHour": 3.0,
              "begin": "300",
              "end": "0420",
              "days": "TTH",
              "roomNumber": 1240,
              "building": "PATRICK TAYLOR",
              "instructor": "BAUMGARTNER G"
          },
          {
              "available": 0,
              "enrollmentCount": 27,
              "abbreviation": "CSC",
              "number": 7700,
              "section": 1,
              "title": "WEB SEARCH & DATA AN",
              "creditHour": 3.0,
              "begin": "900",
              "end": "1020",
              "days": "TTH",
              "roomNumber": 124,
              "building": "TUREAUD HALL",
              "instructor": "SUN M"
          },
          {
              "available": 0,
              "enrollmentCount": 21,
              "abbreviation": "CSC",
              "number": 7700,
              "section": 2,
              "title": "WEB SEC & PEN TEST",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150",
              "days": "TTH",
              "roomNumber": 1240,
              "building": "PATRICK TAYLOR",
              "instructor": "VADREVU K"
          }
      ]
      },
      {
        departmentTitle: "Mathematics",
        courses: [
          {
              "available": 33,
              "enrollmentCount": 7,
              "abbreviation": "MATH",
              "number": 1021,
              "section": 1,
              "title": "COLLEGE ALGEBRA",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "M",
              "roomNumber": 277,
              "building": "LOCKETT",
              "instructor": "WADDELL L"
          },
          {
              "available": 522,
              "enrollmentCount": 83,
              "abbreviation": "MATH",
              "number": 1029,
              "section": 1,
              "title": "INTRO CONTEMP MATH",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "MUFFULETTO M"
          },
          {
              "available": 30,
              "enrollmentCount": 10,
              "abbreviation": "MATH",
              "number": 1029,
              "section": 1,
              "title": "INTRO CONTEMP MATH",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "MUFFULETTO M"
          },
          {
              "available": 205,
              "enrollmentCount": 45,
              "abbreviation": "MATH",
              "number": 1100,
              "section": 1,
              "title": "NATURE OF MATHEMATCS",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 143,
              "building": "COATES",
              "instructor": "DOUGHERTY E"
          },
          {
              "available": 24,
              "enrollmentCount": 14,
              "abbreviation": "MATH",
              "number": 1202,
              "section": 1,
              "title": "GEOM/REASONG/MEASURE",
              "creditHour": 3.0,
              "begin": " 900",
              "end": "1020 ",
              "days": "TTH",
              "roomNumber": 109,
              "building": "COATES",
              "instructor": "DOUGHERTY E"
          },
          {
              "available": 19,
              "enrollmentCount": 11,
              "abbreviation": "MATH",
              "number": 1202,
              "section": 2,
              "title": "GEOM/REASONG/MEASURE",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 109,
              "building": "COATES",
              "instructor": "DOUGHERTY E"
          },
          {
              "available": 23,
              "enrollmentCount": 12,
              "abbreviation": "MATH",
              "number": 1431,
              "section": 1,
              "title": "CAL-BUS & ECO APLCAT",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "LEDET J"
          },
          {
              "available": 14,
              "enrollmentCount": 15,
              "abbreviation": "MATH",
              "number": 1431,
              "section": 2,
              "title": "CAL-BUS & ECO APLCAT",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "LEDET J"
          },
          {
              "available": 0,
              "enrollmentCount": 35,
              "abbreviation": "MATH",
              "number": 1431,
              "section": 3,
              "title": "CAL-BUS & ECO APLCAT",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 101,
              "building": "GYM AUDITORIUM",
              "instructor": "LEDET J"
          },
          {
              "available": 34,
              "enrollmentCount": 6,
              "abbreviation": "MATH",
              "number": 1540,
              "section": 1,
              "title": "INTEGRAL CALCULUS",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 243,
              "building": "LOCKETT",
              "instructor": "ROY A"
          },
          {
              "available": 13,
              "enrollmentCount": 7,
              "abbreviation": "MATH",
              "number": 1540,
              "section": 2,
              "title": "INTEGRAL CALCULUS",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "MWF",
              "roomNumber": 235,
              "building": "LOCKETT",
              "instructor": "VEMPATI N"
          },
          {
              "available": 29,
              "enrollmentCount": 1,
              "abbreviation": "MATH",
              "number": 1550,
              "section": 8,
              "title": "CALCULUS I",
              "creditHour": 5.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "MTWTH",
              "roomNumber": 5,
              "building": "LOCKETT",
              "instructor": "HARHAD A"
          },
          {
              "available": 0,
              "enrollmentCount": 50,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 2,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 930",
              "end": "1020 ",
              "days": "MTWTH",
              "roomNumber": 1022,
              "building": "CAMELLIA HALL",
              "instructor": "HOMAN T"
          },
          {
              "available": 151,
              "enrollmentCount": 39,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 4,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MTWTH",
              "roomNumber": 5,
              "building": "LOCKETT",
              "instructor": "SMOLINSKY L"
          },
          {
              "available": 74,
              "enrollmentCount": 16,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 1,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 730",
              "end": "0820 ",
              "days": "TWTF",
              "roomNumber": 5,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 0,
              "enrollmentCount": 15,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 7,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "TWTF",
              "roomNumber": 116,
              "building": "LOCKETT",
              "instructor": "TU F"
          },
          {
              "available": 44,
              "enrollmentCount": 36,
              "abbreviation": "MATH",
              "number": 1552,
              "section": 8,
              "title": "AN GEOM&CALCULUS-II",
              "creditHour": 4.0,
              "begin": " 500",
              "end": "0650N",
              "days": "TTH",
              "roomNumber": 155,
              "building": "COATES",
              "instructor": "ESTRADA R"
          },
          {
              "available": 0,
              "enrollmentCount": 30,
              "abbreviation": "MATH",
              "number": 1553,
              "section": 1,
              "title": "HON- AN GEOM CAL II",
              "creditHour": 4.0,
              "begin": " 730",
              "end": "0820 ",
              "days": "MTWTH",
              "roomNumber": 276,
              "building": "LOCKETT",
              "instructor": "HOMAN T"
          },
          {
              "available": 0,
              "enrollmentCount": 30,
              "abbreviation": "MATH",
              "number": 1553,
              "section": 2,
              "title": "HON- AN GEOM CAL II",
              "creditHour": 4.0,
              "begin": " 830",
              "end": "0920 ",
              "days": "TWTF",
              "roomNumber": 235,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 28,
              "enrollmentCount": 12,
              "abbreviation": "MATH",
              "number": 2020,
              "section": 1,
              "title": "SOLVING DISCRETE PRO",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 13,
              "enrollmentCount": 6,
              "abbreviation": "MATH",
              "number": 2030,
              "section": 1,
              "title": "DISCRETE DYNAMICALS",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 235,
              "building": "LOCKETT",
              "instructor": "WOLENSKI P"
          },
          {
              "available": 52,
              "enrollmentCount": 28,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 1,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "MWF",
              "roomNumber": 10,
              "building": "LOCKETT",
              "instructor": "SINGH R"
          },
          {
              "available": 43,
              "enrollmentCount": 37,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 2,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 152,
              "building": "COATES",
              "instructor": "TARFULEA A"
          },
          {
              "available": 75,
              "enrollmentCount": 5,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 3,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 6,
              "building": "LOCKETT",
              "instructor": "DRENSKA N"
          },
          {
              "available": 0,
              "enrollmentCount": 80,
              "abbreviation": "MATH",
              "number": 2057,
              "section": 4,
              "title": "MULTIDIMENSIONAL CAL",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250 ",
              "days": "TTH",
              "roomNumber": 228,
              "building": "COATES",
              "instructor": "SCHREVE K"
          },
          {
              "available": 78,
              "enrollmentCount": 2,
              "abbreviation": "MATH",
              "number": 2065,
              "section": 1,
              "title": "EL DIFFERENTIAL EQ",
              "creditHour": 3.0,
              "begin": " 730",
              "end": "0850 ",
              "days": "TTH",
              "roomNumber": 16,
              "building": "LOCKETT",
              "instructor": "RUBIN B"
          },
          {
              "available": 71,
              "enrollmentCount": 9,
              "abbreviation": "MATH",
              "number": 2065,
              "section": 2,
              "title": "EL DIFFERENTIAL EQ",
              "creditHour": 3.0,
              "begin": " 900",
              "end": "1020 ",
              "days": "TTH",
              "roomNumber": 16,
              "building": "LOCKETT",
              "instructor": "RUBIN B"
          },
          {
              "available": 34,
              "enrollmentCount": 46,
              "abbreviation": "MATH",
              "number": 2065,
              "section": 3,
              "title": "EL DIFFERENTIAL EQ",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 109,
              "building": "NICHOLSON",
              "instructor": "MALISOFF M"
          },
          {
              "available": 58,
              "enrollmentCount": 22,
              "abbreviation": "MATH",
              "number": 2070,
              "section": 1,
              "title": "MATH METH IN ENGINEE",
              "creditHour": 4.0,
              "begin": " 930",
              "end": "1020 ",
              "days": "TWTF",
              "roomNumber": 228,
              "building": "COATES",
              "instructor": "OLAFSSON G"
          },
          {
              "available": 58,
              "enrollmentCount": 22,
              "abbreviation": "MATH",
              "number": 2070,
              "section": 2,
              "title": "MATH METH IN ENGINEE",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "TWTF",
              "roomNumber": 228,
              "building": "COATES",
              "instructor": "OLAFSSON G"
          },
          {
              "available": 24,
              "enrollmentCount": 16,
              "abbreviation": "MATH",
              "number": 2085,
              "section": 1,
              "title": "LINEAR ALGEBRA",
              "creditHour": 3.0,
              "begin": "1130",
              "end": "1220 ",
              "days": "MWF",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "HOMAN T"
          },
          {
              "available": 32,
              "enrollmentCount": 48,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 1,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": " 930",
              "end": "1020 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "AZHANG A"
          },
          {
              "available": 50,
              "enrollmentCount": 30,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 2,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "AZHANG A"
          },
          {
              "available": 39,
              "enrollmentCount": 41,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 3,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "AZHANG A"
          },
          {
              "available": 53,
              "enrollmentCount": 27,
              "abbreviation": "MATH",
              "number": 2090,
              "section": 4,
              "title": "ELEM DIFF EQ & LIN A",
              "creditHour": 4.0,
              "begin": " 130",
              "end": "0220 ",
              "days": "TWTF",
              "roomNumber": 145,
              "building": "COATES",
              "instructor": "HAN R"
          },
          {
              "available": 4,
              "enrollmentCount": 36,
              "abbreviation": "MATH",
              "number": 3355,
              "section": 1,
              "title": "PROBABILITY",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 138,
              "building": "LOCKETT",
              "instructor": "LIPTON R"
          },
          {
              "available": 22,
              "enrollmentCount": 3,
              "abbreviation": "MATH",
              "number": 4005,
              "section": 1,
              "title": "GEOMETRY",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 116,
              "building": "LOCKETT",
              "instructor": "DANI P"
          },
          {
              "available": 5,
              "enrollmentCount": 20,
              "abbreviation": "MATH",
              "number": 4023,
              "section": 1,
              "title": "APPLIED ALGEBRA",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 243,
              "building": "LOCKETT",
              "instructor": "COHEN D"
          },
          {
              "available": 10,
              "enrollmentCount": 9,
              "abbreviation": "MATH",
              "number": 4024,
              "section": 1,
              "title": "MATHEMATICAL MODELS",
              "creditHour": 3.0,
              "begin": " 300",
              "end": "0420 ",
              "days": "TTH",
              "roomNumber": 285,
              "building": "LOCKETT",
              "instructor": "MASSATT D"
          },
          {
              "available": 5,
              "enrollmentCount": 14,
              "abbreviation": "MATH",
              "number": 4025,
              "section": 1,
              "title": "OPTIMIZATION THY-APP",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "RIOS ARRIETA"
          },
          {
              "available": 18,
              "enrollmentCount": 1,
              "abbreviation": "MATH",
              "number": 4027,
              "section": 1,
              "title": "DIFFERENTIAL EQU",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 116,
              "building": "LOCKETT",
              "instructor": "RUBIN B"
          },
          {
              "available": 17,
              "enrollmentCount": 21,
              "abbreviation": "MATH",
              "number": 4031,
              "section": 1,
              "title": "ADVANCED CALCULUS I",
              "creditHour": 3.0,
              "begin": " 230",
              "end": "0320 ",
              "days": "MWF",
              "roomNumber": 136,
              "building": "LOCKETT",
              "instructor": "RICHARDSON L"
          },
          {
              "available": 11,
              "enrollmentCount": 8,
              "abbreviation": "MATH",
              "number": 4032,
              "section": 1,
              "title": "ADVANCED CALCULUS II",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1120 ",
              "days": "MWF",
              "roomNumber": 138,
              "building": "LOCKETT",
              "instructor": "RICHARDSON L"
          },
          {
              "available": 17,
              "enrollmentCount": 11,
              "abbreviation": "MATH",
              "number": 4036,
              "section": 1,
              "title": "COMPLEX VARIABLES",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250 ",
              "days": "TTH",
              "roomNumber": 284,
              "building": "LOCKETT",
              "instructor": "ANTIPOV Y"
          },
          {
              "available": 29,
              "enrollmentCount": 11,
              "abbreviation": "MATH",
              "number": 4041,
              "section": 1,
              "title": "SHORTTERM ACT MATH2",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 276,
              "building": "LOCKETT",
              "instructor": "SMOLINSKY L"
          },
          {
              "available": 9,
              "enrollmentCount": 10,
              "abbreviation": "MATH",
              "number": 4058,
              "section": 1,
              "title": "ELEM STOCH PROCESSES",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 113,
              "building": "LOCKETT",
              "instructor": "GANGULY A"
          },
          {
              "available": 12,
              "enrollmentCount": 7,
              "abbreviation": "MATH",
              "number": 4066,
              "section": 1,
              "title": "NUMERICAL DIFF EQ",
              "creditHour": 3.0,
              "begin": "1030",
              "end": "1150 ",
              "days": "TTH",
              "roomNumber": 206,
              "building": "WILLIAMS",
              "instructor": "WAN X"
          },
          {
              "available": 5,
              "enrollmentCount": 14,
              "abbreviation": "MATH",
              "number": 4153,
              "section": 1,
              "title": "FIN DIM VECT SPAC",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "MWF",
              "roomNumber": 134,
              "building": "LOCKETT",
              "instructor": "WU A"
          },
          {
              "available": 13,
              "enrollmentCount": 6,
              "abbreviation": "MATH",
              "number": 4171,
              "section": 1,
              "title": "THEORY OF GRAPHS",
              "creditHour": 3.0,
              "begin": "1230",
              "end": "0120 ",
              "days": "MWF",
              "roomNumber": 112,
              "building": "LOCKETT",
              "instructor": "DING G"
          },
          {
              "available": 18,
              "enrollmentCount": 1,
              "abbreviation": "MATH",
              "number": 4201,
              "section": 1,
              "title": "ABSTRACT ALGEBRA II",
              "creditHour": 3.0,
              "begin": "1200",
              "end": "0120 ",
              "days": "TTH",
              "roomNumber": 243,
              "building": "LOCKETT",
              "instructor": "KOPP G"
          },
          {
              "available": 11,
              "enrollmentCount": 8,
              "abbreviation": "MATH",
              "number": 4325,
              "section": 1,
              "title": "FOURIER TRANSFORMS",
              "creditHour": 3.0,
              "begin": " 130",
              "end": "0250 ",
              "days": "TTH",
              "roomNumber": 285,
              "building": "LOCKETT",
              "instructor": "MASSATT D"
          }
      ],
      },
    ]
  }
];

export const timeIntervals = [
  '7:30 AM',
  '8:00 AM',
  '8:30 AM',
  '9:00 AM',
  '9:30 AM',
  // Add more time intervals here...
];

export const departments = [
  /* 'CSC - Computer Science', */
  /* 'EE - Electrical Engineering', */
  'Computer Science',
  'Mathematics',
]

export const semesters = [
  'Spring 2024',
  "Fall 2023"
]


export const days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
]

export const mapDaysToShortForm: { [longForm: string]: string } = {
  "Monday": "M",
  "Tuesday": "T",
  "Wednesday": "W",
  "Thursday": "H", // it's just H so that it get detected by the filter
  "Friday": "F",
};
